
var myInfo =
{
login: "DinaOC",
id: 11184179,
avatar_url: "https://avatars.githubusercontent.com/u/11184179?v=3",
gravatar_id: "",
url: "https://api.github.com/users/DinaOC",
html_url: "https://github.com/DinaOC",
followers_url: "https://api.github.com/users/DinaOC/followers",
following_url: "https://api.github.com/users/DinaOC/following{/other_user}",
gists_url: "https://api.github.com/users/DinaOC/gists{/gist_id}",
starred_url: "https://api.github.com/users/DinaOC/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/DinaOC/subscriptions",
organizations_url: "https://api.github.com/users/DinaOC/orgs",
repos_url: "https://api.github.com/users/DinaOC/repos",
events_url: "https://api.github.com/users/DinaOC/events{/privacy}",
received_events_url: "https://api.github.com/users/DinaOC/received_events",
type: "User",
site_admin: false,
name: "Dina O'Connor",
company: null,
blog: null,
location: null,
email: null,
hireable: null,
bio: null,
public_repos: 17,
public_gists: 0,
followers: 0,
following: 0,
created_at: "2015-02-24T22:41:57Z",
updated_at: "2016-02-05T15:42:57Z"
}
